trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Checkout@1
  displayName: 'Checkout code'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'serviceson'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create \
        --resource-group $(AZURE_RESOURCE_GROUP) \
        --template-file static-webapp.bicep
